name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-15-intel ]

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest

      - name: CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

      - name: Build
        run: cmake --build build/ --config Release

      - name: Upload Windows build
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build\Release\chroma.exe

      - name: Upload MacOS ARM build
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm-build
          path: build/chroma

      - name: Upload MacOS x86_64 build
        if: ${{ matrix.os == 'macos-15-intel' }}
        uses: actions/upload-artifact@v4
        with:
          name: macos-x86_64-build
          path: build/chroma